import type { GeneratedListing } from '../types/models';

const delay = (ms: number): Promise<void> => {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
};

const mockSuggestions: GeneratedListing[] = [
  {
    title: 'Barely Used Snowblower - Perfect for St. John\'s Winters',
    description:
      'Reliable 2-stage snowblower, starts quickly, handles heavy Newfoundland snowfall with ease. Great condition with only one season of use.',
    category: 'Outdoor',
    price: 875,
  },
  {
    title: 'Solid Wood Dining Table (Seats 6)',
    description:
      'Beautiful solid wood table with minor wear. Perfect for family dinners. Includes matching bench. Pickup in Mount Pearl.',
    category: 'Furniture',
    price: 650,
  },
  {
    title: 'Winter Tire Set - Hyundai Elantra',
    description:
      'Four winter tires with good tread life left. Used for two winters. Stored indoors and ready for the season.',
    category: 'Automotive',
    price: 380,
  },
  {
    title: 'Fujitsu Heat Pump Unit (Working Great)',
    description:
      'Gently used heat pump from home renovation upgrade. Energy efficient and quiet operation. Professional uninstall recommended.',
    category: 'Home Improvement',
    price: 1900,
  },
];

export const generateListingFromImage = async (base64Image: string): Promise<GeneratedListing> => {
  const simulatedLatency = 1600 + Math.floor(Math.random() * 1300);
  await delay(simulatedLatency);

  const isFailure = Math.random() < 0.2;

  if (isFailure) {
    throw new Error('Vision service timeout: AI model did not return a valid response.');
  }

  const seedIndex = base64Image.length % mockSuggestions.length;
  const pickedSuggestion = mockSuggestions[seedIndex];

  return {
    ...pickedSuggestion,
    description: `${pickedSuggestion.description} Auto-generated by SnapSell AI.`,
  };
};
