import type { GeneratedListing } from '../types/models';

export class LlmServiceError extends Error {
  constructor(
    message: string,
    public readonly code: 'TIMEOUT' | 'BAD_RESPONSE',
  ) {
    super(message);
    this.name = 'LlmServiceError';
  }
}

interface GenerateOptions {
  maxRetries?: number;
}

const delay = (ms: number): Promise<void> => {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
};

const mockSuggestions: GeneratedListing[] = [
  {
    title: 'Barely Used Snowblower - Perfect for St. John\'s Winters',
    description:
      'Reliable 2-stage snowblower, starts quickly, handles heavy Newfoundland snowfall with ease. Great condition with only one season of use.',
    category: 'Outdoor',
    price: 875,
  },
  {
    title: 'Solid Wood Dining Table (Seats 6)',
    description:
      'Beautiful solid wood table with minor wear. Perfect for family dinners. Includes matching bench. Pickup in Mount Pearl.',
    category: 'Furniture',
    price: 650,
  },
  {
    title: 'Winter Tire Set - Hyundai Elantra',
    description:
      'Four winter tires with good tread life left. Used for two winters. Stored indoors and ready for the season.',
    category: 'Automotive',
    price: 380,
  },
  {
    title: 'Fujitsu Heat Pump Unit (Working Great)',
    description:
      'Gently used heat pump from home renovation upgrade. Energy efficient and quiet operation. Professional uninstall recommended.',
    category: 'Home Improvement',
    price: 1900,
  },
];

const generateAttempt = async (base64Image: string): Promise<GeneratedListing> => {
  const simulatedLatency = 1400 + Math.floor(Math.random() * 900);
  await delay(simulatedLatency);

  const failedRequest = Math.random() < 0.2;

  if (failedRequest) {
    throw new LlmServiceError('Vision service timeout: AI model did not return a valid response.', 'TIMEOUT');
  }

  const seedIndex = base64Image.length % mockSuggestions.length;
  const pickedSuggestion = mockSuggestions[seedIndex];

  if (!pickedSuggestion) {
    throw new LlmServiceError('AI response could not be parsed.', 'BAD_RESPONSE');
  }

  return {
    ...pickedSuggestion,
    description: `${pickedSuggestion.description} Auto-generated by SnapSell AI.`,
  };
};

export const generateListingFromImage = async (
  base64Image: string,
  options: GenerateOptions = {},
): Promise<GeneratedListing> => {
  const maxRetries = options.maxRetries ?? 0;

  let attempt = 0;
  let lastError: Error | null = null;

  while (attempt <= maxRetries) {
    try {
      return await generateAttempt(base64Image);
    } catch (error) {
      lastError = error instanceof Error ? error : new Error('Unknown LLM service failure');
      attempt += 1;
    }
  }

  throw lastError ?? new Error('Unknown LLM service failure');
};
